### PR TITLE
PLANNER-302-fix: Added beans.xml to enable CDI

### PR DESCRIPTION
**Pull request by oskopek**
Quick fix for PLANNER-302 on JBoss EAP

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Agreed, and this file needs to be deleted (will do so):
https://github.com/droolsjbpm/optaplanner/blob/master/optaplanner-webexamples/src/main/webapp/cloudbalancing/WEB-INF/beans.xml

**Comment by ge0ffrey** [comment]
Must have been a refactor that went wrong

**Comment by oskopek** [comment]
We could also add one beans.xml into `webapp/WEB-INF/beans.xml` and wouldn't have to add each one individually per webexample (depends on what the requirements are - if it needs to be easier to manage or more modular)

**Comment by ge0ffrey** [comment]
the beans.xml only works if it's in `mywarfile.war!WEB-INF/beans.xml`, so only if it's in webapp/WEB-INF/beans.xml`, because WEB-INF (direclty under the root) is a magic directory. However, `cloudbalancing/WEB-INF` is not magic, so the beans.xml in there does nothing: it's just dead weight. Removing now.

**Comment by ge0ffrey** [comment]
Hmm, the fact that you added `vehicleouring/WEB-INF/beans.xml` and that made it work, means that `cloudbalancing/WEB-INF/beans.xml` is indeed being picked up too...

**Pull request merged**
