### PR TITLE
Fixes after IP BOM 7.0.0.CR4 upgrade

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1 Do it needs to be merged at the same time with others?

**Comment by psiroky** [comment]
Yes, all PRs need to be merged together (will add a comment to each of them just to be sure).

**Comment by ge0ffrey** [comment]
ok, can you merge in such occasions?

this is not a one time thing, such a multi-repo merge. We might want to standarize a tag or phrase, for example "multi-repo merge". Which implies that you need a +1 of each repo gatekeeper, but you 'll do the merge yourself - and the gatekeepers shouldn't merge because otherwise they'll break their repo (unless they merge all others too). Wydt?

**Comment by psiroky** [comment]
Yeah, me or @csadilek are usually merging these PRs. We should definitely be putting a clear comment in the PR so that gatekeepers know all the PRs need to be merged at the same time. We could standardize a phrase or something, but not not sure if it is worth it. These kinds of big upgrades are not that common.

**Pull request merged**
