### PR TITLE
PLANNER-554: Revert list size threshold to 16

### PR DESCRIPTION
**Pull request by yurloc**
This change reverts performance loss of chain move selectors in some
cases.

### CODE REVIEW

**Comment by yurloc** [comment]
@ge0ffrey Sorry, I made a typo in PR name and it got linked to a wrong JIRA. Seems I'll have to close this one and open a new one.

**Comment by ge0ffrey** [comment]
no worries - although the commit message is still correct and that indeed gives an incorrect jira link - I am not too stressed about that. I am happy to merge this.
I get stressed about small things in the code - as they stick around and get copy pasted by other developers. Code needs perfection, history doesn't.

**Comment by ge0ffrey** [comment]
Let me know if you're ok with me merging this.

**Comment by yurloc** [comment]
Great! Please go ahead and merge. :rocket:

**Pull request merged**
