### PR TITLE
Enable multiple period deliveries

### PR DESCRIPTION
**Pull request by Darkade**
This patch enables deliveries in multiple periods/days. This allows you to set a customer to be open from, for example, day 1 trough day 3, and other customers to be open just at day 4.

_cvrptwmp-10customers.xml_ has been added. It has 10 customers, each time windowed and with different delivery ranges. It introduces the tag _\<deliveryRangeStart\>_ and _\<deliveryRangeEnd\>_ that specify the days at which the customer is open.

In this example all customers have the same ready and due time, but this is not required.

* Customer 1
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 2    deliveryRangeEnd: 5
* Customer 2
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 2    deliveryRangeEnd: 5
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 2    deliveryRangeEnd: 5
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 2    deliveryRangeEnd: 5
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 1    deliveryRangeEnd: 1
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 1    deliveryRangeEnd: 1
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 0    deliveryRangeEnd: 0
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 0    deliveryRangeEnd: 0
* Customer 3
 * readyTime: 480000    dueTime: 1440000
 * deliveryRangeStart: 0    deliveryRangeEnd: 0

This modifications, do not affect other examples included. But add extra functionality to the VRP examples.

##### Arrival after dueTime
When a vehicle arrives to a customer after the DueTime, the arrivalTime is pushed to the ReadyTime of the Next Day. For Example:

    1. arrivalTime = 1450000, arrivalDay = 0
    2. arrivalTime > dueTime then arrivalTime = 480000, arrivalDay = 1

##### Arrival before deliveryRangeStart
When a vehicle arrives to a customer before the deliveryRangeStart, the arrivalTime is pushed to the readyTime of the first day in the range. For Example:

    1. arrivalTime = 600000, arrivalDay = 0
    2. arrivalDay < deliveryRangeStart then arrivalTime = 480000, arrivalDay = deliveryRangeStart

In every other case, when the arrivalDay is a day inside the range, and the arrivalTime is within the Time Window no changes are made.

#### Drools
The `arrivalAfterDueTime` rule is modified to `arrivalAfterDeliveryRangeEnd` 

The new rule has the same basic behavior, except it penalizes arrival after the last day of the Delivery Range. It doesn't penalize arrival after the dueTime since the modifications made to `ArrivalTimeUpdatingVariableListener.calculateArrivalTime` force all arrivals after the dueTime to the readyTime of the next day

### CODE REVIEW

**Comment by Darkade** [comment]
Made a minor update to describe the patch behavior

**Comment by ge0ffrey** [comment]
ok to test

**Comment by ge0ffrey** [comment]
Thanks Ivan! I 'll take a look and see if we can add this to the current VRP example as-is, or if I'll merge it and immediatly refactor the VRP example into multiple variants, to keep each variant simple enough for users to understand.

**Comment by Darkade** [comment]
Thanks, let me know if there's anything I can do to ease the patch inclusion.

I also noticed that the Jenkins build failed. I'll look into it.

**Comment by Darkade** [comment]
It was failing to build due to some tabs. Corrections made.

**Comment by ge0ffrey** [comment]
Something went very wrong on the branch of the fork. It's apparently merged instead rebased, so it's entirely unclear what the changes are, as there are now thousands of commits.

For a reasonably long time that problem wasn't there, but I never merged because the conflicting tradeoff of making the example richer against making it simply enough to understand for new users. It's a pity I (nor anyone else) took the time to work that through, potentially supporting multiple VRP examples (still not sure if that's a good idea though). Anyway, doesn't matter now, it's ruined, so this PR needs to be closed, sadly. Sorry.

**Comment by pnm** [comment]
, a cx vu cx x

**Pull request closed without merging**
