### PR TITLE
BlockDistribution: minSize should be at least 1

### PR DESCRIPTION
**Pull request by snurkabill**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
In NearbySelectionConfig it currently defaults to 0:
  int sizeMinimum = blockDistributionSizeMinimum == null ? 0 : blockDistributionSizeMinimum;

That will not end up well.

**Comment by ge0ffrey** [comment]
Merging and adjusting default

**Comment by ge0ffrey** [comment]
Thanks for the PR jiri. Would you mind prefixing the bugzilla id (for example "BZ-123456" ) in the commitId next time? Productization etc require that for all commits landing on the release branch that affect production code.

**Comment by snurkabill** [comment]
I didn't know that, sure I can! :) no problem

**Comment by ge0ffrey** [comment]
thanks :)

**Pull request merged**
