### PR TITLE
- converting documentation from Docbook to AsciiDoc

### PR DESCRIPTION
**Pull request by mrietveld**
Voila!

### CODE REVIEW

**Comment by ge0ffrey** [comment]
I love it :) Thanks for this, Marco.

I saw a few small glitches, but I 'll fix these on my end.
We lost JBoss styling, but I don't mind (the default asciidoc style is clearer to read). The side menu is a huge step forward. As well as the other asciidoctor goodness (links for section headers, etc).

One big thing though - how do we generate a PDF? We need something printable. Worst case scenario we generate docbook and push it through the pressgang jboss styles.

**Comment by ge0ffrey** [comment]
@mrietveld The PDF problem can wait (not blocking the merge). The only thing that I need a decision on before the merge is the changed anchorId's: do I need to fix that manually or is it an option during the migration to preserve that (and how much work is to rerun the migration?).

**Comment by ge0ffrey** [comment]
Google analytics I got fixed locally. PDF can probably be fixed with the goldmine here: https://github.com/asciidoctor/asciidoctor-maven-examples

The anchorId decision (manual fix or re-migrate) is the only issue right now :)

**Comment by ge0ffrey** [comment]
I couldn't create a PR on your fork for some reason, so I created a new PR on optaplanner itself (which includes your commit(s):
  https://github.com/droolsjbpm/optaplanner/pull/223

**Comment by mrietveld** [comment]
@ge0ffrey Updated with proper refs (no `_` and camel case). 

Basically had to regenerate the docs (after fixing ref conversion code) and then go through all the differences by hand and merge the new refs.

**Comment by ge0ffrey** [comment]
Thanks Marco :)
Rebasing my changes failed, but after a few failed merges etc, I went with squashing all my commits into 1 and then just cherry picking it to your renewed branch - that went well, only 2 trivial conflicts :)

**Comment by ge0ffrey** [comment]
Closing in favor if this ensemble that includes all of Marco's changes (sorry I had to squash them with mine to avoid png/svg moving etc, hopefully that's not a problem)
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/284
https://github.com/droolsjbpm/optaplanner/pull/224
https://github.com/droolsjbpm/kie-wb-distributions/pull/360

**Pull request closed without merging**
