### PR TITLE
Fail the build!

### PR DESCRIPTION
**Pull request by oskopek**
**Please, don't merge this :)**

### CODE REVIEW

**Comment by oskopek** [comment]
@psiroky let's test it here.

**Comment by psiroky** [comment]
It did not send the e-mail. I will need to take a closer look later.

**Comment by ge0ffrey** [comment]
"Build finished. No test results found. " => Should it say "1 test failed" instead?

**Comment by oskopek** [comment]
@psiroky if you need me to push another broken commit, ping me

**Comment by psiroky** [comment]
"Build finished. No test results found. " this is likely (configuration?) issue with he Pull Request builder plugin. I have it on my todo list to take a look :)

**Comment by psiroky** [comment]
@oskopek thanks. I will probably create my own testing repo and try the new configs there. I don't want to clutter main optaplanner repo and it would also be nice to wait less than 10 minutes for the build result :)

**Comment by oskopek** [comment]
@psiroky sounds like a good idea. Closing this PR. Thanks for investigating.

**Pull request closed without merging**
