### PR TITLE
BAQE-814 - Change revapi to check against 7.14.0.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
depends on kiegroup/droolsjbpm-build-bootstrap#914

### CODE REVIEW

**Comment by rsynek** [comment]
@ge0ffrey Looking at the changes regarding adding type parameter to Score, do we have it documented in the upgrade recipe? I cannot find it.

**Comment by MarianMacik** [comment]
Travis CI failed because it cannot pick up changes from other repositories.

**Comment by ge0ffrey** [comment]
@MarianMacik Sorry for the delay. Yes, good to merge.

**Comment by ge0ffrey** [comment]
> @ge0ffrey Looking at the changes regarding adding type parameter to Score, do we have it documented in the upgrade recipe? I cannot find it.

IIRC Score already had a type parameter, but ScoreHolder didn't. I don't recall making any changes in the examples, (ScoreHolder is only used in the DRL) so I believe no upgrade recipe note is needed. @rsynek Did I miss anything? I do remember that was part of a salvage of a refactor that went haywire, so it's more prone to a mistake.

**Comment by MarianMacik** [comment]
I can include these classes if you don't consider them as APIs. Although it's true that they are in the api package.

**Comment by rsynek** [comment]
> I can exclude these classes if you don't consider them as APIs. Although it's true that they are in the api package.

We probably cannot completely remove this class from revapi checking - due to the usage in DRLs in case of drools score calculation. This particular change is a sort of exception, as DRLs don't care about generic types.

**Comment by rsynek** [comment]
Anyway, nothing holds off merging this PR.

**Pull request merged**
