### PR TITLE
PLANNER-697 Enable property reactive on DroolsScoreDirector

### PR DESCRIPTION
**Pull request by ge0ffrey**
This will fail because of 
https://issues.jboss.org/browse/DROOLS-1368 - Resolved
https://issues.jboss.org/browse/DROOLS-1369

### CODE REVIEW

**Comment by yurloc** [comment]
DROOLS-1368 has a simple workaround. I'm going to investigate DROOLS-1369.

**Comment by ge0ffrey** [comment]
jenkisn please retest this

**Comment by ge0ffrey** [comment]
jenkins please retest this

**Comment by yurloc** [comment]
Jenkins, retest this. The failure should disappear due to droolsjbpm/drools#1095.

**Comment by ge0ffrey** [comment]
@yurloc with this fix, is there a chance QA could run the GeneralBenchmarkApp against the master code with and without this PR? It shouldn't make any difference (because property reactive isn't used). Note that the perf tests aren't useful because they don't do DRL.

**Comment by yurloc** [comment]
@ge0ffrey will do this week.

**Comment by ge0ffrey** [comment]
Jiri's performance benchmark showed no big loss.

**Pull request merged**
